### PR TITLE
Remove deploy rule from travis

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by sbrunner** [comment]
What's the goal of doing this?

**Comment by fredj** [comment]
To simplify; the same can be done manually by running:
```bash
npm version minor
npm publish
```
(+ commit the change in package.json)

**Comment by sbrunner** [comment]
For me it's not a good way to work on, we should have a tag on a release and it the release is build by Travis we have less errors ...

**Comment by fredj** [comment]
`npm version` already creates the git tag and updates the version in `package.json`.

**Pull request merged**
